export const BACKGROUND_PRESETS = [
  {
    id: "violet-portrait",
    name: "Violet portrait",
    source: "https://wall.alphacoders.com/big.php?i=1377813",
    credit: "CelestialCanvas",
    width: 3840,
    height: 2152,
    src: "/backgrounds/violet-portrait.webp",
    thumbnail: "/backgrounds/violet-portrait-thumb.webp",
  },
  {
    id: "blood-moon",
    name: "Blood moon",
    source: "https://backiee.com/wallpaper/samurai-silhouette-against-the-blood-moon/273503",
    credit: "Publisher: FF-NG",
    width: 3840,
    height: 2160,
    src: "/backgrounds/blood-moon.webp",
    thumbnail: "/backgrounds/blood-moon-thumb.webp",
  },
  {
    id: "violet-silhouette",
    name: "Violet silhouette",
    source: "https://tophdwall.com/en/wallpaper/purple-dark-silhouette-4k-wallpaper",
    credit: "Artist not identified by source",
    width: 3840,
    height: 2160,
    src: "/backgrounds/violet-silhouette.webp",
    thumbnail: "/backgrounds/violet-silhouette-thumb.webp",
  },
  {
    id: "neon-close-up",
    name: "Neon close-up",
    source: "https://tophdwall.com/en/wallpaper/4k-ultra-hd-anime-girl-wallpaper-ai-japanese-style",
    credit: "TopHDWall, artist not identified",
    width: 3840,
    height: 2160,
    src: "/backgrounds/neon-close-up.webp",
    thumbnail: "/backgrounds/neon-close-up-thumb.webp",
  },
  {
    id: "makima",
    name: "Makima, ember glow",
    source: "https://hdqwalls.com/makima-the-mysterious-power-wallpaper",
    credit: "flux_ani, credited by HDQWalls",
    width: 3840,
    height: 2160,
    src: "/backgrounds/makima.webp",
    thumbnail: "/backgrounds/makima-thumb.webp",
  },
  {
    id: "glitch-portrait",
    name: "Glitch portrait",
    source: "https://backiee.com/wallpaper/anime/241377",
    credit: "Publisher: Gus",
    width: 3840,
    height: 2160,
    src: "/backgrounds/glitch-portrait.webp",
    thumbnail: "/backgrounds/glitch-portrait-thumb.webp",
  },
  {
    id: "gojo",
    name: "Gojo, violet energy",
    source: "https://hdqwalls.com/wallpaper/3840x2160/satoru-gojo-modern-and-sleek",
    credit: "HDQWalls",
    width: 3840,
    height: 2160,
    src: "/backgrounds/gojo.webp",
    thumbnail: "/backgrounds/gojo-thumb.webp",
  },
  {
    id: "los-santos",
    name: "GTA V, Los Santos after dark",
    source:
      "https://best-wallpaper.net/GTA-5-city-at-night-purple-style-skyscrapers_wallpapers.html",
    credit: "Best Wallpaper",
    width: 3840,
    height: 2160,
    src: "/backgrounds/los-santos.webp",
    thumbnail: "/backgrounds/los-santos-thumb.webp",
  },
  {
    id: "franklin",
    name: "GTA V, Franklin",
    source: "https://www.goodfon.com/games/wallpaper-grand-theft-auto-5-4k.html",
    credit: "GoodFon, uploaded by Dizo1234",
    width: 3840,
    height: 2160,
    src: "/backgrounds/franklin.webp",
    thumbnail: "/backgrounds/franklin-thumb.webp",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk 2077, V in shadow",
    source: "https://wall.alphacoders.com/big.php?i=1021180",
    credit: "Wallpaper Abyss",
    width: 3840,
    height: 2160,
    src: "/backgrounds/cyberpunk.webp",
    thumbnail: "/backgrounds/cyberpunk-thumb.webp",
  },
  {
    id: "ghost-of-tsushima",
    name: "Ghost of Tsushima, masked warrior",
    source: "https://wall.alphacoders.com/big.php?i=1113093",
    credit: "Daniele Ariuolo, credited by Wallpaper Abyss",
    width: 3840,
    height: 2160,
    src: "/backgrounds/ghost-of-tsushima.webp",
    thumbnail: "/backgrounds/ghost-of-tsushima-thumb.webp",
  },
  {
    id: "malenia",
    name: "Elden Ring, Malenia",
    source: "https://pixelz.cc/images/elden-ring-malenia-blade-of-miquella-uhd-4k-wallpaper/",
    credit: "Pixelz",
    width: 3840,
    height: 2160,
    src: "/backgrounds/malenia.webp",
    thumbnail: "/backgrounds/malenia-thumb.webp",
  },
  {
    id: "arkham-knight",
    name: "Batman: Arkham Knight",
    source: "https://hdqwalls.com/wallpaper/3840x2160/batman-arkham-knight-art",
    credit: "HDQWalls",
    width: 3840,
    height: 2160,
    src: "/backgrounds/arkham-knight.webp",
    thumbnail: "/backgrounds/arkham-knight-thumb.webp",
  },
  {
    id: "miles-shadow",
    name: "Spider-Man, Miles in shadow",
    source: "https://hdqwalls.com/spiderman-miles-morales-4k-artwork-wallpaper",
    credit: "_ivantao_, credited by HDQWalls",
    width: 3840,
    height: 2160,
    src: "/backgrounds/miles-shadow.webp",
    thumbnail: "/backgrounds/miles-shadow-thumb.webp",
  },
  {
    id: "miles-red",
    name: "Spider-Man, red and black",
    source: "https://hdqwalls.com/wallpaper/3840x2160/miles-morales-in-red-and-black",
    credit: "HDQWalls",
    width: 3840,
    height: 2160,
    src: "/backgrounds/miles-red.webp",
    thumbnail: "/backgrounds/miles-red-thumb.webp",
  },
  {
    id: "loki",
    name: "Loki, throne of timelines",
    source: "https://wall.alphacoders.com/big.php?i=1385082",
    credit: "Wallpaper Abyss, shared by Jesus Avila",
    width: 3840,
    height: 2160,
    src: "/backgrounds/loki.webp",
    thumbnail: "/backgrounds/loki-thumb.webp",
  },
  {
    id: "alpine-lake",
    name: "Alpine lake",
    source: "https://commons.wikimedia.org/wiki/File:Boathouse_on_a_mountain_lake_(Unsplash).jpg",
    credit: "Luca Bravo",
    width: 3840,
    height: 2560,
    src: "/backgrounds/alpine-lake.webp",
    thumbnail: "/backgrounds/alpine-lake-thumb.webp",
  },
  {
    id: "lake-at-dusk",
    name: "Lake at dusk",
    source: "https://unsplash.com/photos/misty-mountains-over-a-calm-lake-at-dusk-_jxol17cVcQ",
    credit: "Sawyer Bergeron",
    width: 3840,
    height: 2380,
    src: "/backgrounds/lake-at-dusk.webp",
    thumbnail: "/backgrounds/lake-at-dusk-thumb.webp",
  },
  {
    id: "smoky-mountains",
    name: "Smoky mountains",
    source: "https://unsplash.com/photos/znPa4dg4rT8",
    credit: "Brice Cooper",
    width: 3840,
    height: 2560,
    src: "/backgrounds/smoky-mountains.webp",
    thumbnail: "/backgrounds/smoky-mountains-thumb.webp",
  },
] as const;
